
sap.ui.define([], function () {
  "use strict";

  return {
    Configuration: {
      "4400": [
        {
          id: "CUST_MAT_PLANT",
          text: "Customer/Material/Plant",
          fields: [
            "Field_Customer",
            "Field_Material",
            "Column_Plant",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
            "Column_Fixed_Value_Date",
            "Column_Additional_Value_Days",
          ]
        }
      ],
      "4404": [
        {
          id: "CUST_MAT_PLANT",
          text: "Customer/Material/Plant",
          fields: [
            "Field_Customer",
            "Field_Material",
            "Column_Plant",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
            "Column_Fixed_Value_Date",
            "Column_Additional_Value_Days",
          ]
        }
      ],
      "4405": [
        {
          id: "CUST_MAT_PLANT",
          text: "Customer/Material/Plant",
          fields: [
            "Field_Customer",
            "Field_Material",
            "Column_Plant",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
            "Column_Fixed_Value_Date",
            "Column_Additional_Value_Days",
          ]
        }
      ],
      "4407": [
        {
          id: "CUST_MAT_PLANT",
          text: "Customer/Material/Plant",
          fields: [
            "Field_Customer",
            "Field_Material",
            "Column_Plant",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
            "Column_Fixed_Value_Date",
            "Column_Additional_Value_Days",
          ]
        }
      ],
      "44KF": [
        {
          id: "CUST_MAT_PLANT",
          text: "Customer/Material/Plant",
          fields: [
            "Field_Customer",
            "Field_Material",
            "Column_Plant",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
            "Column_Fixed_Value_Date",
            "Column_Additional_Value_Days",
          ]
        }
      ],
      "3304": [
        {
          id: "CUST",
          text: "Customer",
          fields: [
            "Column_Customer",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
            "Column_Fixed_Value_Date",
            "Column_Additional_Value_Days",
          ]
        }
      ],
      "3305": [
        {
          id: "CUST",
          text: "Customer",
          fields: [
            "Column_Customer",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
            "Column_Fixed_Value_Date",
            "Column_Additional_Value_Days",
          ]
        }
      ],
      "3307": [
        {
          id: "CUST",
          text: "Customer",
          fields: [
            "Column_Customer",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
            "Column_Fixed_Value_Date",
            "Column_Additional_Value_Days",
          ]
        }
      ],
      "33KF": [
        {
          id: "CUST",
          text: "Customer",
          fields: [
            "Column_Customer",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
            "Column_Fixed_Value_Date",
            "Column_Additional_Value_Days",
          ]
        }
      ],
      "33PR": [
        {
          id: "CUST",
          text: "Customer",
          fields: [
            "Column_Customer",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
            "Column_Fixed_Value_Date",
            "Column_Additional_Value_Days",
          ]
        }
      ],
      "7777": [
        {
          id: "CUST_MAT_REL",
          text: "Customer/Material with release status",
          fields: [
            "Field_Sales_Organization",
            "Field_Distribution_Channel",
            "Field_Customer",
            "Column_Material",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",

          ]
        }
      ],
      "AMIW": [
        {
          id: "DIV_PRICEGROUP",
          text: "Division/Price Group",
          fields: [
            "Field_Sales_Organization",
            "Field_Distribution_Channel",
            "Field_Division",
            "Column_Price_Group",
            "Column_Description",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
            "Column_Fixed_Value_Date",
            "Column_Additional_Value_Days",

          ]
        }
      ],
      "AMIZ": [
        {
          id: "DIV_PRICEGROUP",
          text: "Division/Price Group",
          fields: [
            "Field_Sales_Organization",
            "Field_Distribution_Channel",
            "Field_Division",
            "Column_Price_Group",
            "Column_Description",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
            "Column_Fixed_Value_Date",
            "Column_Additional_Value_Days",

          ]
        }
      ],
      "ATX1": [
        {
          id: "DEP_DEST",
          text: "Departure Country / Destination Country",
          fields: [
            "Field_Departure_City_Region",
            "Column_Departure_City_Region",
            "Column_Description",
            "Column_Amount",
            "Column_Unit",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Tax_Code",
            "Column_Withholding_Tax_Code",
            "Column_Licence_No",
            "Column_Licence_Date",
            "Column_Deletion_Indictor"
          ]
        },
        {
          id: "DOM_TAX",
          text: "Domestic Taxes",
          fields: [
            "Field_Departure_City_Region",
            "Column_Tax_Class_Customer",
            "Column_Tax_Class_Material",
            "Column_Description",
            "Column_Amount",
            "Column_Unit",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Tax_Code",
            "Column_Withholding_Tax_Code",
            "Column_Licence_No",
            "Column_Licence_Date",
            "Column_Deletion_Indictor",

          ]
        },
        {
          id: "EXP_TAX",
          text: "Export Taxes",
          fields: [
            "Field_Departure_City_Region",
            "Column_Departure_City_Region",
            "Column_Tax_Class_Customer",
            "Column_Tax_Class_Material",
            "Column_Description",
            "Column_Amount",
            "Column_Unit",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Tax_Code",
            "Column_Withholding_Tax_Code",
            "Column_Licence_No",
            "Column_Licence_Date",
            "Column_Deletion_Indictor",

          ]
        }
      ],
      "PB00": [
        {
          id: "SALE_SOLD_MAT_CUST",
          text: "Sales Organisation / Sold-To / Material / Customer",
          fields: [
            "Field_Sales_Organization",
            "Field_Sold_To_Party",
            "Column_Material",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Customer",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
            "Column_Fixed_Value_Date",
            "Column_Additional_Value_Days",
          ]
        },
        {
          id: "SALE_CUST_MAT_ROLE",
          text: "Sales Organisation / Customer / Material / Role",
          fields: [
            "Field_Sales_Organization",
            "Field_Customer",
            "Column_Material",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Partner_Role",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
            "Column_Fixed_Value_Date",
            "Column_Additional_Value_Days",
          ]
        },
        {
          id: "CUST_MAT",
          text: "Customer / Material with release status",
          fields: [
            "Field_Sales_Organization",
            "Field_Distribution_Channel",
            "Field_Customer",
            "Column_Material",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
          ]
        },
        {
          id:"SALE_DIST_MAT_CUST",
          text: "Sales Organisation / Distribution Channel / Material / Mat.Pr.Group / Customer",
          fields: [
            "Field_Sales_Organization",
            "Field_Distribution_Channel",
            "Field_Material",
            "Field_Material_Price_Group",
            "Column_Customer",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
          ]
        },
        {
          id:"PB00_PRICE_CUR_MAT",
          text: "Price list category / Currency / Material with release status",
          fields: [
            "Field_Sales_Organization",
            "Field_Distribution_Channel",
            "Field_Price_List_Type",
            "Field_Document_Currency",
            "Column_Material",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
          ]
        },
        {
          id:"PB00_MAT",
          text: "Material with release status",
          fields: [
            "Field_Sales_Organization",
            "Field_Distribution_Channel",
            "Column_Material",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
          ]
        },
        {
          id:"PB00_SALE_DIST_MAT",
          text: "Sales Organization / Distribution Channel / Material Group",
          fields: [
            "Field_Sales_Organization",
            "Field_Distribution_Channel",
            "Column_Material_Group",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
          ]
        },
        {
          id:"PB00_VEN_MAT",
          text: "Vendor / Material",
          fields: [
            "Field_Supplier",
            "Column_Material",
            "Column_Status",
            "Column_Description",
            "Column_Processing_Status",
            "Column_Amount",
            "Column_Unit",
            "Column_Pricing_Unit",
            "Column_UoM",
            "Column_Calculation_Type",
            "Column_Scale_Base_Type",
            "Column_Valid_From",
            "Column_Valid_To",
            "Column_Deletion",
            "Column_Condition_Supplement",
            "Column_Scales",
            "Column_Texts",
            "Column_Exclusion",
            "Column_Payment_Terms",
          ]
        }
      ]
    }
  };
});